version: "3.9"
services:
 bot:
  build: .
  restart: always
  volumes:
   - '/var/log:/var/log'
  environment:
   - DISCORD_BOTKEY=${DISCORD_BOTKEY}
 db:
  image: redis:6.2.5-alpine
  restart: always
  volumes:
   - '/var/opt/redis:/data'
